apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: gowebserver
  newName: ghcr.io/rafaeljcamara/gowebserver
  newTag: 04575196584735281e213ea69c22d27d3d47a736
